name: Build Windows

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ inputs.tag }}
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false

      - name: Create Windows Zip
        run: |
          Compress-Archive -Path "./src-tauri/target/release/bundle/msi/*" -DestinationPath "app-windows-${{ inputs.tag }}.zip"
        shell: pwsh

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-windows
          path: app-windows-${{ inputs.tag }}.zip
