name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.get_tag.outputs.TAG }}
    steps:
      - id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

  build-windows:
    needs: prepare
    uses: ./.github/workflows/release-windows.yml
    with:
      tag: ${{ needs.prepare.outputs.tag }}

  build-macos:
    needs: prepare
    uses: ./.github/workflows/release-macos.yml
    with:
      tag: ${{ needs.prepare.outputs.tag }}

  create-release:
    needs: [prepare, build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows Artifact
        uses: actions/download-artifact@v3
        with:
          name: app-windows
          path: ./artifacts

      - name: Download macOS Artifact
        uses: actions/download-artifact@v3
        with:
          name: app-macos
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.prepare.outputs.tag }}
          name: Release ${{ needs.prepare.outputs.tag }}
          draft: false
          prerelease: false
          files: |
            ./artifacts/app-windows-${{ needs.prepare.outputs.tag }}.zip
            ./artifacts/app-macos-${{ needs.prepare.outputs.tag }}.zip
