name: Build macOS

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ inputs.tag }}
          releaseName: "App v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false

      - name: Create macOS Zip
        run: |
          cd ./src-tauri/target/release/bundle/dmg
          zip -r "../../../../app-macos-${{ inputs.tag }}.zip" ./*

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-macos
          path: app-macos-${{ inputs.tag }}.zip
